/// Help/manual content -- ported from main.py's _HELP_ES / _HELP_EN lists.
library;

class HelpEntry {
  final String icon, title, body;
  const HelpEntry(this.icon, this.title, this.body);
}

const List<HelpEntry> kHelpEs = [
  HelpEntry('🎂', '¿Qué es Celebria?', 'Celebria es tu recordatorio personal de cumpleaños.\n\nGuarda los datos de tus contactos y te envía una notificación automática cada día a la hora que configures — incluso si la app está completamente cerrada.'),
  HelpEntry('➕', 'Agregar un contacto', '1. Toca + Agregar en la barra inferior.\n2. Escribe el nombre completo (obligatorio).\n3. Elige el Día y el Mes con los menús desplegables (obligatorios).\n   Toca el campo y selecciona el valor de la lista.\n4. El Año es opcional — selecciónalo del desplegable para que la app\n   calcule la edad exacta que cumple esa persona.\n5. Elige la relación: Familia • Amigo/a • Trabajo • Otro\n6. Teléfono, correo electrónico y notas son opcionales.\n7. Toca GUARDAR.'),
  HelpEntry('✏', 'Editar o eliminar un contacto', '• Toca cualquier contacto en la lista para abrir su detalle.\n• Toca EDITAR (arriba a la derecha) para modificar sus datos.\n• Dentro del formulario de edición, toca ELIMINAR para borrarlo.\n• Siempre se pedirá confirmación antes de eliminar.'),
  HelpEntry('🔍', 'Buscar y filtrar contactos', 'En la pantalla Inicio:\n\n• Barra de búsqueda: escribe parte del nombre para filtrar en tiempo real.\n• Botones de categoría: Todos • Familia • Amigos • Trabajo\n\nLos contactos aparecen agrupados automáticamente:\n  🎂 ¡Hoy! — cumpleaños de hoy\n  📅 Esta Semana — próximos 7 días\n  🗓 Próximamente — próximos 8–30 días\n  👥 Todos — el resto del año'),
  HelpEntry('🔔', 'Notificaciones automáticas', 'Celebria envía notificaciones automáticas incluso con la app cerrada.\n\nAl abrir la app, las notificaciones se programan 2 años por adelantado\npara todos tus contactos — sin necesidad de abrir la app cada año.\nSi reinicias el teléfono, se reprograman automáticamente al encender.\n\nTambién aparece un popup dentro de la app el día del cumpleaños.\n\nSi las notificaciones están desactivadas (o falta el permiso de\n\'alarmas exactas\' en Android 12+), Celebria te lo avisa con un aviso\nnativo al abrir la app, con un botón para ir directo a Configuración.\n\nNota: algunos fabricantes bloquean notificaciones por ahorro de batería.\nConsulta \'Batería y notificaciones\' en Configuración si no te llegan.'),
  HelpEntry('⚙', 'Configurar notificaciones', 'Ve a Configuración:\n\nDías de anticipación — elige cuándo quieres el aviso:\n  Hoy • 1 día antes • 3 días antes • 1 semana antes\n\nSegundo recordatorio (opcional) — añade un segundo aviso con otro\nnúmero de días de anticipación. Elige \'Solo uno\' para desactivarlo.\n\nHora del recordatorio — dos desplegables en una sola fila:\n  • Hora: del 00 al 23\n  • Minutos: cualquier minuto, del :00 al :59\nAl seleccionar aparece un aviso con la hora guardada.\n\n🎂 Aviso el día del cumpleaños — activa o desactiva una\nnotificación extra la mañana del cumpleaños.\n\n🔔 Recordar todo el día (opcional) — si lo activas, además del\naviso normal recibirás recordatorios repetidos durante todo el\ndía del cumpleaños, cada 30 min / 1h / 2h / 3h / 4h / 6h (tú eliges\nel intervalo). Apagado por defecto para no molestar.\n\n📋 Resumen mensual — el 1° de cada mes recibes una notificación\ncon la lista de cumpleaños de ese mes.\n\n🔋 Batería y notificaciones — guía para desactivar el ahorro de\nbatería agresivo de tu fabricante (Samsung, Xiaomi, Huawei, etc.)\nque puede bloquear las notificaciones.'),
  HelpEntry('📅', 'Calendario de cumpleaños', 'Toca Calendario en la barra inferior.\n\n• Los días con cumpleaños aparecen resaltados en rosa con 🎂.\n• El día de hoy aparece resaltado en cian.\n• Navega entre meses con los botones ◄  ►.\n• Debajo del calendario verás la lista de cumpleaños del mes.\n\nToca cualquier día resaltado para ir directamente al detalle\ndel contacto. Si hay varios cumpleaños ese día, se mostrará\nuna lista para que elijas cuál quieres ver.\n\nTambién puedes tocar cualquier nombre en la lista inferior\ndel mes para abrir directamente el detalle de ese contacto.'),
  HelpEntry('💬', 'Botón de WhatsApp', 'Si un contacto tiene número de teléfono guardado:\n\n1. Toca el contacto para abrir su detalle.\n2. Toca WhatsApp.\n3. WhatsApp se abrirá directamente en esa conversación.\n\nPerfecto para enviar un mensaje de felicitación en segundos 🎉\n\nFormato recomendado: incluye el código de país sin el +\n  República Dominicana: 18095551234\n  Estados Unidos:       12125551234'),
  HelpEntry('📤', 'Exportar e importar contactos', 'Ve a Configuración → Respaldo de Datos:\n\nExportar JSON: guarda todos tus contactos en Celebria_backup.json en la carpeta Descargas de tu teléfono.\n\nImportar JSON: lee el archivo Celebria_backup.json de Descargas y agrega esos contactos a la app.\n\nIdeal para copias de seguridad o pasar tus datos a un teléfono nuevo.'),
  HelpEntry('📱', 'Importar desde tu Agenda', 'Si quieres agregar varios contactos que ya tienen cumpleaños en tu teléfono:\n\n1. En tu app de Contactos, exporta tus contactos a un archivo .vcf (vCard). El nombre suele ser \'Contacts.vcf\' o similar.\n2. En Celebria, ve a Configuración → Respaldo de Datos → Importar desde Agenda (.vcf).\n3. Selecciona el archivo .vcf exportado.\n4. Celebria encontrará solo los contactos con cumpleaños registrados.\n5. Marca cuáles quieres importar y toca IMPORTAR SELECCIONADOS.\n\nSolo se importan contactos que tengan Día y Mes en el archivo.\nSi el año está incluido, la app calculará la edad automáticamente.'),
  HelpEntry('🌐', 'Cambiar el idioma', 'Toca el botón EN que aparece en la esquina superior derecha de cualquier pantalla.\n\nEl idioma cambia instantáneamente en toda la app y se recuerda la próxima vez que la abras.\n\nPara volver al español, toca ES en la misma posición.'),
  HelpEntry('🔄', 'Cómo actualizar la app', 'Celebria revisa automáticamente si hay versión nueva cada vez que\nla abres (necesita internet). Si hay actualización, aparece un aviso\nen la pantalla de Inicio unos segundos después de abrir la app.\n\n── Paso a paso para actualizar ─────────────────────\n\n1. Toca el botón  ⬇ Descargar  en el aviso.\n   Se abrirá Chrome con una página de descarga.\n\n2. En esa página busca el archivo que dice\n   \'Celebria-vX.X.X.apk\'  y tócalo.\n   (Está listado como un archivo adjunto en la página.)\n\n3. Chrome descargará el archivo.\n   Verás una barra de progreso abajo de la pantalla.\n   Espera a que diga  \'Listo\'  o  \'Abrir\'.\n\n4. Toca  \'Abrir\'  (o ve a Descargas y toca el archivo .apk).\n\n5. Android te preguntará si quieres instalar la app.\n   Toca  INSTALAR.\n\n6. Si Android dice \'No se permite instalar de esta fuente\':\n   • Toca  Configuración  en ese aviso.\n   • Activa  \'Permitir de esta fuente\'.\n   • Regresa y toca  INSTALAR  nuevamente.\n   (Esto es normal — la app no está en la Play Store.)\n\n7. Al terminar toca  ABRIR  para usar la versión nueva.\n\n── Si tomas \'Ahora no\' ──────────────────────────────\nLa próxima vez que abras Celebria con internet, el aviso\nvolverá a aparecer para que puedas actualizar.\n\n── Actualización obligatoria ────────────────────────\nSi el botón aparece en rojo y no hay opción \'Ahora no\',\nes una actualización requerida. Debes instalarla para\ncontinuar usando la app.\n\nSi no ves ningún aviso, ya tienes la versión más reciente.'),
  HelpEntry('📸', 'Foto de contacto', 'Cada contacto puede tener una foto personalizada:\n\n1. Abre el formulario de Agregar o Editar contacto.\n2. En la sección Foto toca Agregar foto.\n3. Selecciona cualquier imagen de tu galería o almacenamiento.\n4. La foto se guarda localmente — sin subir a ningún servidor.\n\nSi no hay foto, se muestra un círculo con la inicial del nombre en el color de la relación (cian=Familia, verde=Amigo, etc.).\n\nToca Quitar foto en el formulario para eliminarla.'),
  HelpEntry('🎁', 'Nota de regalo', 'Guarda ideas de regalo para cada contacto:\n\n1. Abre el formulario de Agregar o Editar contacto.\n2. En el campo Nota de regalo escribe lo que se te ocurra.\n   Ejemplo: \'Le gusta el café colombiano\' o \'Talla M de camiseta\'.\n\nLa nota aparece en el detalle del contacto con el ícono 🎁.\nNo hay límite de caracteres — escribe todo lo que necesites recordar.'),
  HelpEntry('📊', 'Estadísticas rápidas', 'Ve a Configuración → Estadísticas para ver un resumen:\n\n• Total de contactos registrados\n• Cuántos cumplen hoy, esta semana y este mes\n• El próximo cumpleaños con los días que faltan\n• Distribución por tipo de relación (Familia, Amigos, Trabajo, Otro)\n• Gráfica de barras con la distribución de cumpleaños por mes\n• ✨ Cumpleaños especiales — contactos que cumplen 15, 18, 21, 25,\n  30, 40, 50, 60, 70, 75, 80, 90 o 100 años este año\n• ♈ Signos del zodiaco — distribución de tus contactos por signo\n  con símbolo, nombre y barra de porcentaje\n\nEl mes actual aparece resaltado en cian.'),
  HelpEntry('💡', 'Consejos útiles', '• Agrega el año de nacimiento para ver la edad exacta que cumple cada persona.\n\n• El color del borde de cada tarjeta indica la urgencia:\n   Rosa neón = HOY  •  Amarillo = esta semana  •  Cian = próximos 30 días\n\n• ✨ Borde amarillo doble = cumpleaños redondo este año (15, 18, 21, 25, 30...)\n\n• 🗓 El chip \'Este mes\' en Inicio muestra cuántos cumplen en el mes actual.\n  Tócalo para ir directo al Calendario del mes.\n\n• Toca un día rosado en el Calendario para ir directo al detalle del contacto.\n\n• Agrega notas como \'¿Le gusta el chocolate?\' para recordar qué regalarle.\n\n• Usa la categoría Trabajo para cumpleaños de colegas.\n\n• El archivo JSON de respaldo es texto plano — puedes abrirlo en cualquier editor.'),
];

const List<HelpEntry> kHelpEn = [
  HelpEntry('🎂', 'What is Celebria?', 'Celebria is your personal birthday reminder.\n\nStore your contacts\' birthdays and receive a birthday popup every time you open the app — never miss an important date again.'),
  HelpEntry('➕', 'Adding a contact', '1. Tap + Add in the bottom bar.\n2. Enter the full name (required).\n3. Choose the birthday Day and Month from the dropdown menus (required).\n   Tap the field and pick the value from the list.\n4. Year is optional — select it from the dropdown so the app can\n   calculate the exact age the person is turning.\n5. Choose the relationship: Family • Friend • Work • Other\n6. Phone, email, and notes are optional.\n7. Tap SAVE.'),
  HelpEntry('✏', 'Editing or deleting a contact', '• Tap any contact in the list to open their detail view.\n• Tap EDIT (top right) to modify their information.\n• Inside the edit form, tap DELETE to remove them.\n• A confirmation prompt always appears before deleting.'),
  HelpEntry('🔍', 'Search and filter', 'On the Home screen:\n\n• Search bar: type part of a name to filter in real time.\n• Category buttons: All • Family • Friends • Work\n\nContacts are automatically grouped by:\n  🎂 Today! — today\'s birthdays\n  📅 This Week — next 7 days\n  🗓 Coming Soon — next 8–30 days\n  👥 All — the rest of the year'),
  HelpEntry('🔔', 'Automatic notifications', 'Celebria sends notifications automatically even when the app is closed.\n\nWhen you open the app, notifications are scheduled 2 years in advance\nfor all your contacts — no need to open the app every year.\nIf you restart your phone, notifications are rescheduled automatically.\n\nA birthday popup also appears inside the app on the day itself.\n\nIf notifications are disabled (or the \'exact alarms\' permission is\nmissing on Android 12+), Celebria shows a native prompt when you open\nthe app, with a button that goes straight to Settings.\n\nNote: some manufacturers block notifications via battery optimization.\nSee \'Battery & notifications\' in Settings if alerts are not arriving.'),
  HelpEntry('⚙', 'Configuring notifications', 'Go to Settings:\n\nAdvance days — choose when to be notified:\n  Same day • 1 day before • 3 days before • 1 week before\n\nSecond reminder (optional) — add a second alert on a different number\nof advance days. Choose \'Just one\' to disable it.\n\nReminder time — two dropdowns in a single row:\n  • Hour: 00 to 23\n  • Minutes: any minute, :00 to :59\nA confirmation toast appears showing the saved time.\n\n🎂 Birthday-day notification — enable or disable an extra\nnotification on the morning of the birthday itself.\n\n🔔 Remind all day (optional) — turn this on to get repeated\nreminders throughout the birthday day itself, every 30 min / 1h /\n2h / 3h / 4h / 6h (you choose the interval). Off by default so it\nnever nags you unless you want it to.\n\n📋 Monthly summary — on the 1st of every month you receive a\nnotification listing that month\'s upcoming birthdays.\n\n🔋 Battery & notifications — step-by-step guide to disable\naggressive battery optimization from your manufacturer\n(Samsung, Xiaomi, Huawei, etc.) that may block notifications.'),
  HelpEntry('📅', 'Birthday calendar', 'Tap Calendar in the bottom bar.\n\n• Days with birthdays are highlighted in pink with 🎂.\n• Today is highlighted in cyan.\n• Use ◄  ► to navigate between months.\n• Below the calendar, see the complete list of birthdays for the month.\n\nTap any highlighted day to go directly to that contact\'s detail view.\nIf multiple contacts share the day, a list will appear so you can\npick which one to open.\n\nYou can also tap any contact name in the list below the calendar\nto open their detail view directly.'),
  HelpEntry('💬', 'WhatsApp button', 'If a contact has a phone number saved:\n\n1. Tap the contact to open their detail view.\n2. Tap WhatsApp.\n3. WhatsApp will open directly in that conversation.\n\nPerfect for sending a quick birthday message in seconds 🎉\n\nRecommended format: include the country code without the +\n  Dominican Republic: 18095551234\n  United States:      12125551234'),
  HelpEntry('📤', 'Exporting and importing contacts', 'Go to Settings → Data Backup:\n\nExport JSON: saves all your contacts to Celebria_backup.json in your phone\'s Downloads folder.\n\nImport JSON: reads Celebria_backup.json from your Downloads folder and adds those contacts to the app.\n\nIdeal for backups or transferring your data to a new phone.'),
  HelpEntry('📱', 'Import from your Contacts', 'To quickly add contacts that already have birthdays saved on your phone:\n\n1. In your Contacts app, export your contacts to a .vcf (vCard) file. It is usually named \'Contacts.vcf\' or similar.\n2. In Celebria, go to Settings → Data Backup → Import from Contacts (.vcf).\n3. Select the exported .vcf file.\n4. Celebria will find only contacts that have a birthday registered.\n5. Check which ones you want and tap IMPORT SELECTED.\n\nOnly contacts with a birthday Day and Month in the file are imported.\nIf the year is included, the app will calculate the age automatically.'),
  HelpEntry('🌐', 'Changing the language', 'Tap the ES button in the top-right corner of any screen.\n\nThe language changes instantly throughout the app and is remembered the next time you open it.\n\nTo switch back to English, tap EN in the same position.'),
  HelpEntry('🔄', 'How to update the app', 'Celebria automatically checks for a new version every time you open\nit (requires internet). If an update is available, a notice appears\non the Home screen a few seconds after opening the app.\n\n── Step-by-step update guide ───────────────────────\n\n1. Tap the  ⬇ Download  button in the notice.\n   Chrome will open a download page.\n\n2. On that page, look for the file named\n   \'Celebria-vX.X.X.apk\'  and tap it.\n   (It is listed as an attached file on the page.)\n\n3. Chrome will download the file.\n   A progress bar will appear at the bottom of the screen.\n   Wait until it says  \'Done\'  or  \'Open\'.\n\n4. Tap  \'Open\'  (or go to Downloads and tap the .apk file).\n\n5. Android will ask if you want to install the app.\n   Tap  INSTALL.\n\n6. If Android says \'Install blocked\' or \'Unknown source\':\n   • Tap  Settings  in that prompt.\n   • Enable  \'Allow from this source\'.\n   • Go back and tap  INSTALL  again.\n   (This is normal — the app is not on the Play Store.)\n\n7. When done, tap  OPEN  to start using the new version.\n\n── If you tap \'Not now\' ────────────────────────────\nThe next time you open Celebria with internet, the notice\nwill appear again so you can update.\n\n── Mandatory update ────────────────────────────────\nIf the button appears in red and there is no \'Not now\' option,\nthe update is required. You must install it to keep using the app.\n\nIf no notice appears, you already have the latest version.'),
  HelpEntry('📸', 'Contact photo', 'Each contact can have a personalized photo:\n\n1. Open the Add or Edit contact form.\n2. In the Photo section, tap Add photo.\n3. Select any image from your gallery or storage.\n4. The photo is saved locally — never uploaded to any server.\n\nWithout a photo, a colored circle with the name\'s initial is shown in the relationship color (cyan=Family, green=Friend, etc.).\n\nTap Remove photo in the form to clear it.'),
  HelpEntry('🎁', 'Gift note', 'Save gift ideas for each contact:\n\n1. Open the Add or Edit contact form.\n2. In the Gift note field, write whatever comes to mind.\n   Example: \'Loves Colombian coffee\' or \'Size M t-shirt\'.\n\nThe note appears in the contact detail view with the 🎁 icon.\nNo character limit — write as much as you need to remember.'),
  HelpEntry('📊', 'Quick Statistics', 'Go to Settings → Statistics for a summary:\n\n• Total contacts registered\n• How many have birthdays today, this week, and this month\n• The next upcoming birthday with days remaining\n• Breakdown by relationship type (Family, Friends, Work, Other)\n• Bar chart of birthday distribution across months\n• ✨ Milestone birthdays — contacts turning 15, 18, 21, 25, 30,\n  40, 50, 60, 70, 75, 80, 90 or 100 this year\n• ♈ Zodiac signs — distribution of your contacts by sign,\n  with symbol, name, and percentage bar\n\nThe current month is highlighted in cyan.'),
  HelpEntry('💡', 'Useful tips', '• Add the birth year to see the exact age each person is turning.\n\n• The card border color shows urgency:\n   Neon pink = TODAY  •  Yellow = this week  •  Cyan = next 30 days\n\n• ✨ Double amber border = milestone birthday this year (15, 18, 21, 25, 30...)\n\n• 🗓 The \'This month\' chip on Home shows how many birthdays fall in the\n  current month. Tap it to jump straight to the Calendar for that month.\n\n• Tap a pink day in the Calendar to jump straight to that contact\'s detail.\n\n• Add notes like \'Likes chocolate?\' to remember gift ideas.\n\n• Use the Work category for colleagues to keep them separate from friends.\n\n• The JSON backup file is plain text — you can open it in any editor.'),
];